@startuml
class Accion{
+Ejecutar[]
}

class Movimiento{
+Mover[]
}

class Colision{
+Detectar[]
}

class Danio{
+Ataca[]
}

class Juego{
+EstadoJuego
+Iniciar()
}

class Nivel{
+EstadoNivel
+Cargar()
}

class Zona{
+EstadoZona
}

class Entidad{
-PosicionX 
-PosicionY 
+EstadoActivo 
+Actualizar()
}

class Personaje{
-Velocidad 
+EstadoMovimiento 
+Mover()
}

class Sonic{
-Energia 
+EstadoAtaque
+Atacar()
}

class Enemigo{
-Danio 
+EstadoHostil
+Atacar()
}

class Badnik{
-Programa 
+EstadoRobot 
}

class DoctorEggman{
-Plan 
+EstadoControl 
}

class Objeto{
-EstadoInterno 
+EstadoExterno 
+AplicarEfecto()
}

class Anillo{
-Valor 
+EstadoVisible
}

class Monitor{
-Contenido
+EstadoRoto
}

class Escudo{
-Duracion 
+EstadoProteccion
}

class Invencibilidad{
-Duracion 
+EstadoActivo 
}

class ZapatillaVelocidad{
-Duracion 
+EstadoRapido 
}

class VidaExtra{
-Cantidad 
+EstadoDisponible 
}

class PuntoControl{
-Registro 
+EstadoActivo 
}

class EsmeraldaCaos{
-Energia 
+EstadoMagico 
}

class Plataforma{
-MovimientoInterno 
+EstadoSoporte 
}

class Resorte{
-Fuerza 
+EstadoSalto
}

class Pincho{
-Danio 
+EstadoPeligro
}

class Bloque{
-Resistencia 
+EstadoSolido 
}

class Teletransportador{
-Destino 
+EstadoActivo
}

class Lava{
-Temperatura 
+EstadoPeligro 
}

class MotorFisica{
-Gravedad 
+EstadoMotor 
+Calcular()
}

class SistemaColision{
-Algoritmo
+EstadoDeteccion
+Detectar()
}

class Maquina{
-Energia 
+EstadoOperacion 
}

class MemoriaJuego{
-DatoInterno 
+DatoGuardado 
+Guardar()
+Cargar()
}

class Vida{
-Cantidad 
+EstadoVida
}

class Inventario{
-Capacidad 
+EstadoInventario 
}

Personaje --|> Entidad
Objeto --|> Entidad

Sonic --|> Personaje
Enemigo --|> Personaje

Badnik --|> Enemigo
DoctorEggman --|> Enemigo

Anillo --|> Objeto
Monitor --|> Objeto
Escudo --|> Objeto
Invencibilidad --|> Objeto
ZapatillaVelocidad --|> Objeto
VidaExtra --|> Objeto
PuntoControl --|> Objeto
EsmeraldaCaos --|> Objeto
Plataforma --|> Objeto
Resorte --|> Objeto
Pincho --|> Objeto
Bloque --|> Objeto
Teletransportador --|> Objeto
Lava --|> Objeto

Objeto ..|> Accion
Objeto ..|> Colision

Personaje ..|> Movimiento
Personaje ..|> Colision

Enemigo ..|> Danio

Juego *-- "1..*" Nivel
Nivel *-- "1..*" Zona

Zona *-- "1" Sonic
Zona *-- "1..*" Enemigo
Zona *-- "0..*" Objeto

Sonic *-- "1" Vida
Sonic *-- "1" Inventario

Inventario *-- "0..50" Anillo

DoctorEggman *-- "1" Maquina

Juego *-- "1" MemoriaJuego

Personaje ..> MotorFisica
Personaje ..> SistemaColision

Enemigo ..> Sonic

@enduml