@startuml
class Juego
class Nivel
class Entidad
class Personaje
class Sonic
class Enemigo
class Badnik
class DoctorEggman
class Objeto
class Vida
class Inventario
class MotorFisica
class SistemaColision
class Maquina

Personaje --|> Entidad
Objeto --|> Entidad
Sonic --|> Personaje
Enemigo --|> Personaje
Badnik --|> Enemigo
DoctorEggman --|> Enemigo

class Anillo
class Monitor
class Escudo
class Invencibilidad
class ZapatillaVelocidad
class VidaExtra
class PuntoControl
class EsmeraldaCaos
class Plataforma
class Resorte
class Pincho
class BloqueRompible
class Bomba
class Barril
class Interruptor
class Puerta
class Llave
class Teletransportador
class Elevador
class Canon
class Bloque
class Reloj
class Caja
class Trampa
class Vagon
class Portal
class PlataformaMovil
class Muro
class Agua
class Lava

Anillo --|> Objeto
Monitor --|> Objeto
Escudo --|> Objeto
Invencibilidad --|> Objeto
ZapatillaVelocidad --|> Objeto
VidaExtra --|> Objeto
PuntoControl --|> Objeto
EsmeraldaCaos --|> Objeto
Plataforma --|> Objeto
Resorte --|> Objeto
Pincho --|> Objeto
BloqueRompible --|> Objeto
Bomba --|> Objeto
Barril --|> Objeto
Interruptor --|> Objeto
Puerta --|> Objeto
Llave --|> Objeto
Teletransportador --|> Objeto
Elevador --|> Objeto
Canon --|> Objeto
Bloque --|> Objeto
Reloj --|> Objeto
Caja --|> Objeto
Trampa --|> Objeto
Vagon --|> Objeto
Portal --|> Objeto
PlataformaMovil --|> Objeto
Muro --|> Objeto
Agua --|> Objeto
Lava --|> Objeto

Juego *-- "1..*" Nivel
Nivel *-- "1" Sonic
Nivel *-- "1..*" Enemigo
Nivel *-- "0..*" Objeto

Sonic *-- "1" Vida
Sonic *-- "1" Inventario
Inventario *-- "0..50" Anillo
DoctorEggman *-- "1" Maquina

Personaje ..> MotorFisica
Personaje ..> SistemaColision
Enemigo ..> "1" Sonic

@enduml