@startuml
interface IMovible {
  +Mover()
}

interface IColisionable {
  +DetectarColision()
}

interface IInteractuable {
  +Interactuar()
}

interface IDanable {
  +RecibirDanio()
}

class Entidad {
  -x : float
  -y : float
  -activo : boolean
  +Actualizar()
}

class Personaje {
  -velocidad : float
  -direccion : int
  +Mover()
  +Atacar()
}

class Sonic {
  -energia : int
  -anillos : int
  +Saltar()
}

class Enemigo {
  -danio : int
  -estadoIA : String
  +Atacar()
}

class Badnik
class DoctorEggman {
  -fase : int
}

class Objeto {
  -estadoInterno : String
  -visible : boolean
  +AplicarEfecto()
}

class Vida {
  -cantidad : int
  +Restar()
  +Sumar()
}

class Inventario {
  -anillos : int
  +AgregarAnillo()
  +PerderAnillos()
}

class MotorFisica {
  -gravedad : float
  -friccion : float
  +AplicarFisica()
}

class SistemaColision {
  -precision : float
  +VerificarColision()
}

class Maquina {
  -resistencia : int
  +Destruir()
}

class MemoriaJuego {
  -progresoGeneral : String
  +GuardarJuego()
  +CargarJuego()
}

class MemoriaNivel {
  -enemigosRestantes : int
  -objetosActivos : int
  +GuardarEstadoNivel()
}

class MemoriaJugador {
  -anillosGuardados : int
  -vidasGuardadas : int
  +GuardarEstadoJugador()
}

class Anillo {
  -valor : int
  +Recolectar()
}

class Monitor {
  -tipoPowerUp : String
  +Romper()
}

class Escudo {
  -durabilidad : int
  +Proteger()
}

class VidaExtra {
  -usada : boolean
}

class PuntoControl {
  -activado : boolean
}

class Plataforma {
  -movil : boolean
}

class Resorte {
  -fuerza : float
}

class Pincho {
  -danio : int
}

class BloqueRompible {
  -resistencia : int
}

class Lava {
  -temperatura : float
}

class Juego
class Nivel

Personaje --|> Entidad
Objeto --|> Entidad
Sonic --|> Personaje
Enemigo --|> Personaje
Badnik --|> Enemigo
DoctorEggman --|> Enemigo

Anillo --|> Objeto
Monitor --|> Objeto
Escudo --|> Objeto
VidaExtra --|> Objeto
PuntoControl --|> Objeto
Plataforma --|> Objeto
Resorte --|> Objeto
Pincho --|> Objeto
BloqueRompible --|> Objeto
Lava --|> Objeto

Personaje ..|> IMovible
Personaje ..|> IColisionable
Personaje ..|> IDanable

Objeto ..|> IColisionable
Objeto ..|> IInteractuable

Enemigo ..|> IDanable

Juego *-- "1..*" Nivel
Juego *-- "1" MemoriaJuego

Nivel *-- "1" Sonic
Nivel *-- "1..*" Enemigo
Nivel *-- "0..*" Objeto
Nivel *-- "1" MemoriaNivel

Sonic *-- "1" Vida
Sonic *-- "1" Inventario
Sonic *-- "1" MemoriaJugador

Inventario *-- "0..50" Anillo
DoctorEggman *-- "1" Maquina

Personaje ..> MotorFisica
Personaje ..> SistemaColision
Enemigo ..> "1" Sonic

@enduml